import { Schema } from 'express-validator';
import {
  VALIDATION_BIKE,
  VALIDATION_BUDGET,
  VALIDATION_CATEGORY,
  VALIDATION_DESTINATION,
  VALIDATION_EVENTDETAIL,
  VALIDATION_ID,
  VALIDATION_IMAGE,
  VALIDATION_NUMBEROFACCEPT,
  VALIDATION_SHAREWITH,
  VALIDATION_TAG,
  VALIDATION_TITLE,
} from '../../../constants/validation';

