
export const touringMessages={
    "touring/user-not-found": "User not found",
    "touring/invalid-email": "Invalid email",
    "touring/weak-password": "Password is too weak",
    "touring/email-already-in-use": "Email already in use",
    "touring/argument-error": "Argument error",
    "touring/expired-action-code": "Expired action code",
    "touring/invalid-action-code": "Invalid action code",
    "touring/user-disabled": "User disabled",
    "touring/invalid-verification-code": "Invalid verification code",
    "touring/invalid-verification-id": "Invalid verification id",
    "unauthorized": "Unauthorized",
    "notAdmin": "You are not authorized to access this resource",
    "notFound": "Resource not found",
    "internalServerError": "Internal server error",
    "invalidToken": "Invalid token",
    "touring/wrong-password": "Wrong password",
    "touring/invalid-credential": "Invalid credential",
    "touring/operation-not-allowed": "Operation not allowed",
}
